### ISSUE TITLE
Coh3 Stats opens in tiny window

### ISSUE THREAD

**Issue by jeremynpross** [cohstats/coh3-stats-desktop-app#185]
On my Alienware Area 51 R5 desktop, Windows 10 and Dell 4k monitor scaling to 175%, Coh3 Stats open in a tiny window. See screenshot.

It is hard to grab the resize arrow although eventually I can  -- then I drag it out to a normal size. Maximizing the tiny window works but that is not my desired behavior. It opens to a normal size on my other PCs with 2k or standard 1920 x 1080 monitors.

Reinstalling does not help. Neither does changing the resolution or scaling. Deleting COH 3 and reinstalling both the game and the stats app used to correct the problem but does not fix it anymore.

Please let me know if the devs can fix this or offer a workaround.

![Coh3 Stats Opens in tiny window](https://github.com/user-attachments/assets/be15a10e-30c4-481d-a4aa-bc7e46917650)

**Comment by petrvecera** [comment]
While the app is quit. You can delete this folder `C:\Users\<USER>\AppData\Local\com.coh3stats.desktop\EBWebView` as well as `C:\Users\<USER>\AppData\Roaming\com.coh3stats.desktop`

This issues should be fixed in the next release.

**Comment by jeremynpross** [comment]
I deleted the folder and contained files. Opened app again. It flashed about 1/3 of a second at the right size and immediately popped down to the tiny window. Retried deletion you suggested. Now just opens in the tiny window.

I am glad you will fix this in next release. I will test and report.

**Comment by petrvecera** [comment]
Hi @jeremynpross could you please test out this build? 

I assume it will still open the small window - but when you resize and quit - it should open the right size. 

Thank you 🙏 

https://github.com/cohstats/coh3-stats-desktop-app/releases/download/1.5.4/Coh3.Stats.Desktop.App_1.5.4_x64_en-US.msi
https://github.com/cohstats/coh3-stats-desktop-app/releases/tag/1.5.4

**Comment by jeremynpross** [comment]
Thanks for asking me to test this build.

This functions as you expected. The first run open the tiny window but resizing to desired size & position, closing and reopening displays Coh3 Stats at the last resized size & position (after a flash of opening at medium-size to the left).

As usual, Windows tries to block the unknown installer from running and requires approval in More Info, and Norton 360 tries to block and analyze the exe running but ends up calling it Safe. This is not a blocking bug for me because I know the workarounds, but would be good to fix for most users.

**Comment by petrvecera** [comment]
Awesome, thank you 🙏 

Unknown installer issue - the cheapest code signing certificates are usually around 200$/year. Unfortunately we don't have a budget for that.

**Comment by jeremynpross** [comment]
I admire what you can do even with no budget! No worries, gamers figure these things out.

I am pleased to be a tester anytime. I used to develop games as a producer/tester. Text me at 323 896 1708 as I don't usually stay on Github long.

**Comment by petrvecera** [comment]
Thank you 🙏 Please let me know if you spot any other issues with the app!

Should be fixed in 1.6.0
