### ISSUE TITLE
Only allow 1 running instance

### ISSUE THREAD

**Issue by JohannesMerkt** [cohstats/coh3-stats-desktop-app#20]
The app should not be able to run twice on a system, to avoid unanticipated conflicts

**Comment by petrvecera** [comment]
FYI: How we did this in past with some old frameworks without any support:

1# Running instances creates file pid.txt where is system process id of the running task 
2# When you start the app, it checks the file,
-  if it doesn't exists -> create
- if it exists --> check if there is process running under that PID ,
    - if yes, quit 
    - if no, start create new file
