### ISSUE TITLE
Feature Request: Show Battlegroups

### ISSUE THREAD

**Issue by xtc0r** [cohstats/coh3-stats-desktop-app#26]
Could you also show the picked Battegroups? The data is available for every player when looking in the gamelist. Would be nice directly show it in the desktop app.

**Comment by JohannesMerkt** [comment]
At the moment I think this is impossible. The app is checking the log files of the game to find out what players are currently in the game. Then it makes an request to a relic api to get additional data. sadly no battlegroups are available there

**Comment by JohannesMerkt** [comment]
Also I am not sure if this can be considered as "gaining an unfair advantage over players without the app". Such features will not be implemented

**Comment by xtc0r** [comment]
I would say as long as you can also see it ingame in the "Game List" menu it's not unfair as the information is available for everybody. But I also can understand your view.

**Comment by JohannesMerkt** [comment]
Yeah that one isn't an obvious one to decide. Let's if future patches even allow me to get this information and or if the commander picked view changes ingame
