### ISSUE TITLE
[Feature Request] Display Active Players in Game Count without having to find the game first. 

### ISSUE THREAD

**Issue by R4md4c** [cohstats/coh3-stats-desktop-app#76]
When the desktop app starts, a modal loading indicator is shown, but the active player count isn't displayed until a game is found. 

A nice QoL change is to display the active player count without waiting for a game. I find this information to be useful as it might be give me a clue why I'm taking too long to find a game.

**Comment by petrvecera** [comment]
@R4md4c thanks for suggestion, this will be fixed in the next release 👍
