### ISSUE TITLE
Game State (Closed) When Open, Will not show any new games. 

### ISSUE THREAD

**Issue by Blueprint-Sensei** [cohstats/coh3-stats-desktop-app#91]
Good afternoon,

I have an issue where my Game State says Closed even though I have the game open and it will not show me any new games. I have logged in and out and restarted my PC many times, I've also reinstalled the game and the app multiple times. I've disabled anti virus and changed the install directory of the app. I am at a loss as to what to do. I've even deleted the playback folder etc. Any assistance or advice would be greatly appreciated as I love your app. 

For reference I am on the newest version 1.4. And the app is not even showing the steam account I am currently logged into.

**Comment by petrvecera** [comment]
Hi, 

It takes the game state from the warnings.log, the default path is:
```
C:\Users\pagep\Documents\My Games\Company of Heroes 3\warnings.log
```
But sometimes when you have Dropbox or OneDrive installed the path might be different. Try changing this path. 

![image](https://github.com/cohstats/coh3-stats-desktop-app/assets/8086995/5243da31-3732-4f6b-b23a-bf60f4e97009)

![image](https://github.com/cohstats/coh3-stats-desktop-app/assets/8086995/df5733f6-1108-4e47-8040-623f781073b9)

**Comment by Blueprint-Sensei** [comment]
> Hi,
> 
> It takes the game state from the warnings.log, the default path is:
> 
> ```
> C:\Users\pagep\Documents\My Games\Company of Heroes 3\warnings.log
> ```
> 
> But sometimes when you have Dropbox or OneDrive installed the path might be different. Try changing this path.
> 
> ![image](https://private-user-images.githubusercontent.com/8086995/318395620-5243da31-3732-4f6b-b23a-bf60f4e97009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjU1MzMsIm5iZiI6MTcxMTk2NTIzMywicGF0aCI6Ii84MDg2OTk1LzMxODM5NTYyMC01MjQzZGEzMS0zNzMyLTRmNmItYjIzYS1iZjYwZjRlOTcwMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMDk1MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU0OWE0ZDVlYmU5ZDY4MjExY2VkMDdmYTg1Yjk3MjA2NmY4MjI3NjVjOWQyNDBmYmY2ZmI2MjE4NTAwYjAzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.07IkjkPPAIWMSGhND3zWYuG0-DU_NRmEIvWW2sF-wx0)
> 
> ![image](https://private-user-images.githubusercontent.com/8086995/318396095-df5733f6-1108-4e47-8040-623f781073b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjU1MzMsIm5iZiI6MTcxMTk2NTIzMywicGF0aCI6Ii84MDg2OTk1LzMxODM5NjA5NS1kZjU3MzNmNi0xMTA4LTRlNDctODA0MC02MjNmNzgxMDczYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMDk1MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzc5OGEyMDg2MjM3NzBiN2EwZWVkZWVmYTZiNDg2Y2VlZmFkZjU2NzZiYmMxMGNkMjYyMzRlZDgwZWJkNGVkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V4A2Q6pD15OKwjlpBYQ15WNRply-nu0vzXbdj6lq8xA)

OMG Thank you! It was because I uninstalled one drive :o 
I changed the path and it worked!!!! :D
